--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/shinra/wallpapers/19.jpg"

-- Special
background="#161d1c"
foreground="#cedbd7"
cursor="#cedbd7"

-- Colors
color0="#161d1c"
color1="#D8A06B"
color2="#E9CF72"
color3="#708B8C"
color4="#AAA28D"
color5="#D4B293"
color6="#EDD2A3"
color7="#cedbd7"
color8="#909996"
color9="#D8A06B"
color10="#E9CF72"
color11="#708B8C"
color12="#AAA28D"
color13="#D4B293"
color14="#EDD2A3"
color15="#cedbd7"
