# Shell variables
# Generated by 'wal'
wallpaper='/home/shinra/wallpapers/19.jpg'

# Special
background='#161d1c'
foreground='#cedbd7'
cursor='#cedbd7'

# Colors
color0='#161d1c'
color1='#D8A06B'
color2='#E9CF72'
color3='#708B8C'
color4='#AAA28D'
color5='#D4B293'
color6='#EDD2A3'
color7='#cedbd7'
color8='#909996'
color9='#D8A06B'
color10='#E9CF72'
color11='#708B8C'
color12='#AAA28D'
color13='#D4B293'
color14='#EDD2A3'
color15='#cedbd7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
